# Generated by Django 3.1.6 on 2021-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='int_set',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='int_set',
            name='set_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='int_set',
            name='user_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
