# Generated by Django 3.1.6 on 2021-03-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0002_auto_20210304_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Int_Set',
            new_name='Integers',
        ),
    ]
