# Generated by Django 3.1.6 on 2021-03-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0003_auto_20210304_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='integers',
            name='session_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
