# Generated by Django 3.1.6 on 2021-03-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('integers', '0004_integers_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('X', models.IntegerField(default=0)),
                ('q', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integers.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Integers',
        ),
        migrations.AddField(
            model_name='integer',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integers.set'),
        ),
        migrations.AlterUniqueTogether(
            name='integer',
            unique_together={('set_id', 'index')},
        ),
    ]
