# Generated by Django 3.1.6 on 2021-03-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0005_auto_20210325_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='IntegerSet',
        ),
    ]
