# Generated by Django 3.1.6 on 2021-03-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('integers', '0006_auto_20210328_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integer',
            name='set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integers', to='integers.integerset'),
        ),
        migrations.AlterField(
            model_name='integerset',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_sets', to='integers.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authtoken.token'),
        ),
    ]
