# Generated by Django 3.1.6 on 2021-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integers', '0008_auto_20210407_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integerset',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integer_sets', to='integers.persistentsession'),
        ),
    ]
